version: 0.2

env:
  variables:
    STAGE: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g serverless@3
  pre_build:
    commands:
      - cd backend
      - npm install --no-audit --no-fund
  build:
    commands:
      - serverless deploy --stage $STAGE
