version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
  pre_build:
    commands:
      - cd backend
      - npm ci || npm install --no-audit --no-fund
      - npx serverless@3 --version
  build:
    commands:
      - : "${STAGE:=dev}"         
      - echo "Deploying to $STAGE"
      - npx serverless@3 deploy --stage "$STAGE"
