version: 0.2

phases:
  install:
    commands:
      # 1) Instalar nvm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

      # 2) Exportar NVM_DIR y cargar nvm en este shell
      - export NVM_DIR="$HOME/.nvm"
      - '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'

      # 3) Persistir para los siguientes comandos/fases
      - echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
      - echo '. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - source $BASH_ENV

      # 4) Instalar y verificar Node 20
      - nvm install 20
      - node -v && npm -v

  pre_build:
    commands:
      - source $BASH_ENV
      - cd backend
      - npm ci || npm install --no-audit --no-fund
      - npx serverless@3 --version

  build:
    commands:
      - source $BASH_ENV
      - : "${STAGE:=dev}"       
      - echo "Deploying to $STAGE"
      - npx serverless@3 deploy --stage "$STAGE"
