version: 0.2

env:
  variables:
    NVM_DIR: /root/.nvm

phases:
  install:
    commands:
      - echo "Instalando Node 20 con nvm..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - . "$NVM_DIR/nvm.sh"
      - nvm install 20
      - node -v
      - npm -v

  pre_build:
    commands:
      - . "$NVM_DIR/nvm.sh"
      - cd backend
      - npm ci || npm install --no-audit --no-fund
      - npx serverless@3 --version

  build:
    commands:
      - . "$NVM_DIR/nvm.sh"
      - : "${STAGE:=dev}"           
      - echo "Deploying to $STAGE"
      - npx serverless@3 deploy --stage "$STAGE"
