version: 0.2

env:
  variables:
    # Valor por defecto; CodePipeline/CodeBuild lo puede sobreescribir con la variable de entorno STAGE
    STAGE: dev

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v

  pre_build:
    commands:
      # Entra al backend donde está serverless.yml
      - cd backend
      # Instala dependencias; si no hay package-lock, cae al npm install
      - npm ci || npm install --no-audit --no-fund
      - npx serverless@3 --version

  build:
    commands:
      - echo "Deploying to ${STAGE}"
      - npx serverless@3 deploy --stage "${STAGE}"

  post_build:
    commands:
      - echo "Build completed on $(date)"
