version: 0.2

phases:
  install:
    commands:
      - node -v
      - npm -v

  pre_build:
    commands:
      - cd backend
      # usa npm ci si hay lockfile; si no, npm install
      - if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
      - npx serverless@3 --version

  build:
    commands:
      - : "${STAGE:=dev}"        # (opcional) default a 'dev' si STAGE no viene del entorno
      - echo "Deploying to ${STAGE}"
      - npx serverless@3 deploy --stage "${STAGE}"

  post_build:
    commands:
      - echo "Build completed on $(date)"
